#!/bin/bash
#Updating the path to executor instance
path_exec='"path":"//"'
new_path_exec='"path":"/home/ubuntu/projects/executor/"'
sudo sed -i "s%$path_exec%$new_path_exec%g" /home/ubuntu/projects/support/config/default.json

#Verifying the instance queue
#Finding the current ip
IP=$(hostname -I | awk '{print $1}')
#172.31.1.41 Ari Testing Instance
testingInstance="172.31.20.165"
stagingInstance="172.31.12.113"
testingInstanceTmp="172.31.1.41"#ari-testing

if [[ "$IP" == $testingInstance || "$IP" == $testingInstanceTmp ]]; then
    echo "It's the testing instance"
    #Change queue name
    sudo sed -i 's/portal.muuktest.com/testing.muuktest.com/g' /home/ubuntu/projects/executor/mkcli.py
elif [[ "$IP" == $stagingInstance ]]; then
    echo "It's the staging instance"
    #Change queue name
    sudo sed -i 's/portal.muuktest.com/staging.muuktest.com/g' /home/ubuntu/projects/executor/mkcli.py
fi